-- ORDER_INFO 에서 DESTINATION 컬럼 제거 (납품처가 아이템별로 이동됨)
ALTER TABLE ORDER_INFO DROP COLUMN DESTINATION;

-- ORDER_ITEM 에 DESTINATION, NOTE 컬럼 추가
ALTER TABLE ORDER_ITEM ADD COLUMN DESTINATION VARCHAR(500);
ALTER TABLE ORDER_ITEM ADD COLUMN NOTE TEXT;
